version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: graphql
    versions:
    - 1.12.3
    - 1.12.4
    - 1.12.5
    - 1.12.6
    - 1.12.7
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: aws-sdk-sqs
    versions:
    - 1.35.0
    - 1.36.0
    - 1.37.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
