services:
  postgres:
    ports:
      - "5433:5432"

  app:
    ports:
      !override
      - "4000:80"
    environment:
      - "RAILS_ENV=development"
      - "REDIS_URL=redis://redis:6379"
      - "DATABASE_URL=postgresql://caesar:caesar@postgres/caesar_development"
      - "LD_PRELOAD="
