:verbose: false
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 10 %>
:timeout: 30
:queues:
  - [internal, 40]
  - [default, 30]
  - [external, 20]
  - [batch, 10]
  - [tess, 1]
