:verbose: false
#:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 10 %>
:timeout: 30
:queues:
  - [internal, 4]
  - [default, 3]
  - [external, 2]
  - [batch, 1]
