:verbose: false
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 10 %>
:timeout: 30
:queues:
  - [internal, 400]
  - [default, 300]
  - [external, 200]
  - [batch, 100]
  - [tess, 1]
