:verbose: <%= !!ENV.fetch('SIDEKIQ_VERBOSE', false) %>
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10).to_i %>
:timeout:  <%= ENV.fetch('SIDEKIQ_TIMEOUT', 25).to_i %>
:queues:
  - [internal, 4]
  - [default, 3]
  - [external, 2]
  - [batch, 1]
