ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.3.8'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets', '~> 4.1'
gem 'middleman-syntax', '~> 3.2'
gem 'nokogiri', '~> 1.14.3'
gem 'redcarpet', '~> 3.5.1'
gem 'rouge', '~> 3.20'
gem 'sass'

gem "webrick", "~> 1.8"
