ruby '>=3.2'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.5'
gem 'middleman-autoprefixer'
gem 'middleman-sprockets'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'rack', '~> 2.2.21'
gem 'redcarpet'
gem 'rouge', '~> 3.28.0'
gem 'sass'

gem "webrick", "~> 1.7"
