name: Deploy to Production

on:
  push:
    tags:
      - production-release
  workflow_dispatch:

jobs:
  db_migration_production:
    name: Production DB Migration
    uses: zooniverse/ci-cd/.github/workflows/db_migration.yaml@main
    with:
      app_name: caesar
      environment: production
      commit_id: ${{ github.sha }}
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  deploy_production:
    name: Deploy to Production
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    needs: db_migration_production
    with:
      app_name: caesar
      repo_name: caesar
      commit_id: ${{ github.sha }}
      environment: production
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_production
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Production / deploy_app
      status: ${{ needs.deploy_production.result }}
      title: "Caesar Production deploy & migration complete"
      title_link: "https://caesar.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
