name: Run Tests
on:
  pull_request: # run tests for all PRs
  push: { branches: master } # only run tests on push / merges to master branch

env:
  DATABASE_URL_TEST: postgresql://postgres:postgres@localhost/caesar_test

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    continue-on-error: true
    strategy:
      matrix:
        gemfile:
          - Gemfile
          - Gemfile.next
        ruby:
          - 2.7
          - 3.0
        exclude:
          - gemfile: Gemfile
            ruby: 3.0
          - gemfile: Gemfile.next
            ruby: 2.7
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for focus specs
        run: ./scripts/no_focus.sh

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup test database
        run: RAILS_ENV=test bin/rails db:create

      - name: Run tests
        run: RAILS_ENV=test bundle exec rspec # avoid running spring via bin/rspec binstub
