name: Run Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          DATABASE_URL_TEST: postgresql://postgres:postgres@localhost/caesar_test
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          DATABASE_URL_TEST: postgresql://postgres:postgres@localhost/caesar_test
        run: bin/rspec
